
package Forms;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Arrecis
 */
public class FrmCrear_Usuario extends javax.swing.JFrame {
   
   private final ImageIcon logo = new ImageIcon("umg.png");
   private JFileChooser buscar = new JFileChooser();
   private File usuario;
   private Path origenPath,destinoPath;
   private FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPEG/PNG","jpeg","png","jpg");
   private ImageIcon user = new ImageIcon("user.png");
   private String Nombre="",Correo="",Pass="",Pass2="",Ruta="",NombreArchivo="user.png",Carpeta="UMGMEMORYGAME1.0";
   String clave="",RolEmpleado="null",codigo="000";
   Cifrado cifrar = new Cifrado();
   private String[] datos= null;

    public ImageIcon getUser() {
        foto.setIcon((new ImageIcon(user.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_SMOOTH))));
        return user;
    }

    public void setUser(ImageIcon user) {
        this.user = user;
    }
   private final JLabel fuentes = new JLabel();
  
    public FrmCrear_Usuario() {
        initComponents();
        letras();
        umg.setIcon((new ImageIcon(logo.getImage().getScaledInstance(umg.getWidth(),umg.getHeight(),Image.SCALE_SMOOTH ))));
        foto.setIcon((new ImageIcon(user.getImage().getScaledInstance(foto.getWidth(),foto.getHeight(),Image.SCALE_SMOOTH ))));
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
//        public void leer() {
//        String contenido, clave, user;
// 
//        System.out.println(Pass);
//        try {
//            FileReader lectura = new FileReader(usuario);
//            BufferedReader lector = new BufferedReader(lectura);
//            contenido = lector.readLine();
//            while (contenido != null) {
//                try {
//                    contenido = lector.readLine();
//                    datos = contenido.split(",");
//                    clave = cifrar.decifrar(datos[2]);
//                    user =  cifrar.decifrar(datos[1]);
//                    codigo= cifrar.decifrar(datos[3]);
//
////                    if ((correo.equals(user)) && (Pass.equals(clave))) {
////                        JOptionPane.showMessageDialog(null, "BIENVENIDO");
////                        FrmJuego ventana = new FrmJuego();
////                        ventana.datos(datos[3], cifrado.decifrar(datos[0])); //cifrado.decifrar(user)
////                        ventana.setVisible(true);
////                        dispose();
////                    }
//
//                } catch (Exception e) {
//                    System.out.println("Error. " + e);
//                }
//            }
//
//        } catch (FileNotFoundException ex) {
//            System.out.println("erro> " + ex);
//        } catch (IOException ex) {
//            System.out.println("erro> " + ex);
//        }
//    }
     public final void letras(){
    
        try{
            Letrero ver,ver2;
            
           ver = new Letrero("¡BIENVENIDO A UMG MEMORY GAME 1.0!",1000,this.letras, this.fuente);
           ver2 = new Letrero("Crear Nuevo Usuario",1000,this.letras2, this.fuentes);
           ver.start();
           ver2.start();
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Error " + ex.getMessage());
        }
    
    }
     
    public void obtenerRegistro(){
        FileWriter escribir = null;
        String temp="";
       try {
           usuario = new File("Users.txt");
           escribir = new FileWriter(usuario,true);
           System.out.println(nombre.getText());
           Nombre = cifrar.cifrar(nombre.getText());
           System.out.println(Nombre);
           System.out.println(apellidos.getText());
           Correo = cifrar.cifrar(apellidos.getText());
           codigo = CodigoEmpleado.getText();
           System.out.println(apellidos);
           //clave = cifrar.cifrar(Pass);
           temp =Nombre+","+Correo+","+Pass+","+codigo+","+RolEmpleado+","+NombreArchivo;
           escribir.write(temp);
           escribir.write("\r\n");           
           escribir.close();
           JOptionPane.showMessageDialog(null,"Registrando los datos del Empleado "+cifrar.decifrar(Nombre));
           limpiarRegistro();
           regresar();
           
       } catch (IOException ex) {
           Logger.getLogger(FrmCrear_Usuario.class.getName()).log(Level.SEVERE, null, ex);
       } 
       
    }
     
    private void validarRango(){
       RolEmpleado = (String) tipoEmpleado.getSelectedItem();
        if(RolEmpleado.endsWith("Seleccionar")){
            JOptionPane.showMessageDialog(null,"Rango de Empleado por defecto");
            RolEmpleado="Encargado";
        }
        
    }
    public void validarPassword(){
        Pass = "";
        Pass2 ="";
        validarRango();
        for(int i = 0; i<contraseña.getPassword().length;i++){
        Pass += contraseña.getPassword()[i];
        }
        for(int i = 0; i<contraseña2.getPassword().length;i++){
        Pass2 += contraseña2.getPassword()[i];
        }
        if(Pass==""&& Pass2==""){
            JOptionPane.showMessageDialog(null,"NECESITAS COLOCAR UNA CONTRASEÑA");
            Pass="!";
        }
        
       if(Pass.equals(Pass2)){
           Pass = cifrar.cifrar(Pass2);
           obtenerRegistro();
       }
       else{
           System.err.println("1.."+Pass);
           System.err.println("2.."+Pass2);
           JOptionPane.showMessageDialog(null,"Las contraseñas no son iguales T.T ");
           JOptionPane.showMessageDialog(null,"Reiniciando formulario por seguridad..");
           contraseña.setText("");
           contraseña2.setText("");
           
           
       }
    }
     
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        umg = new javax.swing.JLabel();
        fuente = new javax.swing.JLabel();
        letras = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        letras2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellidos = new javax.swing.JTextField();
        contraseña = new javax.swing.JPasswordField();
        contraseña2 = new javax.swing.JPasswordField();
        foto = new javax.swing.JLabel();
        CambiarAvatar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CodigoEmpleado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tipoEmpleado = new javax.swing.JComboBox<>();
        RegresarMenu = new javax.swing.JButton();
        registrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fuente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fuente.setText("jLabel1");

        letras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letras.setText("jLabel1");

        letras2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letras2.setText("jLabel1");

        jLabel1.setText("Nombres");

        jLabel2.setText("Apellidos");

        jLabel3.setText("Contraseña");

        jLabel4.setText("Confirma Contraseña");

        foto.setText("jLabel5");

        CambiarAvatar.setText("Busca Fotografia");
        CambiarAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarAvatarActionPerformed(evt);
            }
        });

        jLabel5.setText("Codigo de Empleado");

        jLabel6.setText("Tipo de Empleado");

        tipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Engargado", "Gerente" }));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(umg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fuente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(letras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(CambiarAvatar))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(letras2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(55, 55, 55)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(apellidos)
                                    .addComponent(nombre)
                                    .addComponent(CodigoEmpleado, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(contraseña2)
                                    .addComponent(contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                    .addComponent(tipoEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(90, 90, 90)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(fuente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letras, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(umg, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letras2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CambiarAvatar))
                .addGap(34, 34, 34)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(tipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(31, 31, 31))
                            .addComponent(jLabel4))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        RegresarMenu.setText("Regresar");
        RegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarMenuActionPerformed(evt);
            }
        });

        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegresarMenu)
                .addGap(95, 95, 95)
                .addComponent(registrar)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrar)
                    .addComponent(RegresarMenu))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
       validarPassword();
    }//GEN-LAST:event_registrarActionPerformed

    private void CambiarAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarAvatarActionPerformed
        try {
            buscar.setFileFilter(filtro);
            int opcion = buscar.showOpenDialog(this);
            if (opcion == JFileChooser.APPROVE_OPTION) {
                NombreArchivo = buscar.getSelectedFile().getName();
                Ruta = buscar.getSelectedFile().getPath();
                System.out.println("nombreARchivo: "+NombreArchivo);
                
               //user = new ImageIcon(NombreArchivo);
                System.out.println("ruta: "+Ruta);
                origenPath = FileSystems.getDefault().getPath(Ruta);
                destinoPath = FileSystems.getDefault().getPath(NombreArchivo);
            }

            Files.copy(origenPath, destinoPath, StandardCopyOption.REPLACE_EXISTING);
            setUser(new ImageIcon(NombreArchivo));
            foto.setIcon((new ImageIcon(user.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_SMOOTH))));
        } catch (IOException e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_CambiarAvatarActionPerformed

    private void RegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarMenuActionPerformed
       regresar();
    }//GEN-LAST:event_RegresarMenuActionPerformed
    
   public void regresar(){
       
   }
   private void limpiarRegistro(){
       setUser(new ImageIcon("user.png"));
       foto.setIcon((new ImageIcon(user.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_SMOOTH))));
       this.nombre.setText("");
       this.apellidos.setText("");
       this.CodigoEmpleado.setText("");
       this.tipoEmpleado.setSelectedIndex(0);
       this.contraseña.setText("");
       this.contraseña2.setText("");
   }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCrear_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCrear_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCrear_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCrear_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCrear_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CambiarAvatar;
    private javax.swing.JTextField CodigoEmpleado;
    private javax.swing.JButton RegresarMenu;
    private javax.swing.JTextField apellidos;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JPasswordField contraseña2;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel fuente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel letras;
    private javax.swing.JLabel letras2;
    private javax.swing.JTextField nombre;
    private javax.swing.JPanel panel;
    private javax.swing.JButton registrar;
    private javax.swing.JComboBox<String> tipoEmpleado;
    private javax.swing.JLabel umg;
    // End of variables declaration//GEN-END:variables
}
